using System.ComponentModel;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Purview.SourceGeneratorFramework.Helpers;

[EditorBrowsable(EditorBrowsableState.Never)]
public static class IncrementalGeneratorInitializationContextExtensions
{
	extension(IncrementalGeneratorInitializationContext context)
	{
		/// <summary>
		/// Registers the <c>Microsoft.CodeAnalysis.EmbeddedAttribute</c> source using a <see cref="CodeWriter"/>.
		/// </summary>
		/// <param name="generatorName">The generator name to stamp into the generated source.</param>
		/// <param name="generatorVersion">The optional generator version.</param>
		/// <param name="fileName">The source file name.</param>
		public void RegisterEmbeddedAttribute(
			string generatorName,
			string? generatorVersion = null,
			string fileName = "EmbeddedAttribute.g.cs"
		)
		{
			if (string.IsNullOrWhiteSpace(generatorName))
				throw new ArgumentException("Generator name cannot be null or whitespace.", nameof(generatorName));

			context.RegisterPostInitializationOutput(spc =>
			{
				CodeWriter writer = new(generatorName, generatorVersion ?? "1.0.0.0");
				writer.WriteAutoGeneratedHeader();
				writer.WriteFileScopedNamespace(
					PurviewTypeLibrary.Microsoft.CodeAnalysis.EmbeddedAttribute.AsTypeReference()
				);

				// The compiler treats this special type as implicitly compiler-generated and embedded,
				// so no generated attributes are applied here.
				writer.WriteClass(
					new(PurviewTypeLibrary.Microsoft.CodeAnalysis.EmbeddedAttribute)
					{
						IsSealed = true,
						IsPartial = true,
						BaseType = PurviewTypeLibrary.System.Attribute,
						IncludeGeneratedAttributes = false,
					},
					bodyWriter =>
						bodyWriter.Comment(
							"This is a special type that is treated as implicitly compiler-generated and embedded by the compiler."
						)
				);

				spc.AddSource(fileName, SourceText.From(writer.ToString(), Encoding.UTF8));
			});
		}
	}
}
