// <auto-generated />

namespace Purview.SourceGeneratorFramework.Testing.Generators;

#nullable enable

/// <summary>Generates parsing members for an attribute-data model.</summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
[global::Microsoft.CodeAnalysis.Embedded]
sealed class GenerateAttributeDataModelAttribute : global::System.Attribute
{
	/// <summary>Initializes the attribute for the target attribute type.</summary>
	public GenerateAttributeDataModelAttribute(global::System.Type targetAttribute)
	{
		TargetAttribute =
			targetAttribute ?? throw new global::System.ArgumentNullException(nameof(targetAttribute));
	}

	/// <summary>Initializes the attribute for the target attribute type name.</summary>
	public GenerateAttributeDataModelAttribute(string targetAttribute)
	{
		TargetAttributeName =
			targetAttribute ?? throw new global::System.ArgumentNullException(nameof(targetAttribute));
	}

	/// <summary>Gets the attribute type represented by the generated model.</summary>
	public global::System.Type? TargetAttribute { get; }

	/// <summary>Gets the attribute type name represented by the generated model.</summary>
	public string? TargetAttributeName { get; }

	/// <summary>Gets or sets whether derived attribute types are accepted.</summary>
	public bool MatchByInheritance { get; set; }

	/// <summary>Gets or sets whether constructor and named properties are discovered automatically.</summary>
	public bool AutoDiscover { get; set; }
}

/// <summary>Describes how a generated model property is read from Roslyn attribute data.</summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
[global::Microsoft.CodeAnalysis.Embedded]
sealed class AttributePropertyAttribute : global::System.Attribute
{
	/// <summary>Initializes a new instance of the <see cref="AttributePropertyAttribute"/> class.</summary>
	/// <param name="source">The source of the attribute value.</param>
	public AttributePropertyAttribute(
		AttributePropertySource source = AttributePropertySource.NamedArgument
	)
	{
		Source = source;
	}

	/// <summary>Gets or sets the source of the attribute value.</summary>
	public AttributePropertySource Source { get; set; } = AttributePropertySource.NamedArgument;

	/// <summary>Gets or sets an optional constructor parameter or named-property mapping.</summary>
	public string? Name { get; set; }

	/// <summary>Gets or sets the constructor argument index.</summary>
	public int Index { get; set; } = -1;

	/// <summary>Gets or sets the value used by the generated empty model.</summary>
	public object? DefaultValue { get; set; }
}

/// <summary>Identifies the source used to populate an attribute model property.</summary>
[global::Microsoft.CodeAnalysis.Embedded]
enum AttributePropertySource
{
	/// <summary>Reads a named attribute argument.</summary>
	NamedArgument,

	/// <summary>Reads a constructor argument by ordinal index.</summary>
	ConstructorIndex,

	/// <summary>Reads a constructor argument by parameter name.</summary>
	ConstructorName,

	/// <summary>Populates another generated attribute-data model from the same attribute.</summary>
	NestedModel,
}
