<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<AssemblyName>$(RootNamespace)</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SourceGeneratorFramework\SourceGeneratorFramework.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="/" Visible="true" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
	</ItemGroup>
</Project>
