<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);IncludeSourceGeneratorShared</TargetsForTfmSpecificContentInPackage>
		<IsPackable>true</IsPackable>
		<AssemblyName>$(RootNamespace)</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SourceGeneratorFramework\SourceGeneratorFramework.csproj" />
		<ProjectReference
			Include="..\SourceGeneratorShared\SourceGeneratorShared.csproj"
			PrivateAssets="all"
			Pack="false"
		/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
		<PackageReference
			Include="Microsoft.CodeAnalysis.CSharp.Workspaces"
			VersionOverride="$(RoslynCompilerVersion)"
		/>
	</ItemGroup>

	<Target Name="IncludeSourceGeneratorShared">
		<MSBuild
			Projects="..\SourceGeneratorShared\SourceGeneratorShared.csproj"
			Targets="GetTargetPath"
			Properties="Configuration=$(Configuration);TargetFramework=netstandard2.0"
		>
			<Output TaskParameter="TargetOutputs" ItemName="_SourceGeneratorSharedAssembly" />
		</MSBuild>

		<ItemGroup>
			<_SourceGeneratorSharedPackageFile Include="@(_SourceGeneratorSharedAssembly)" />
			<_SourceGeneratorSharedPackageFile Include="@(_SourceGeneratorSharedAssembly->'%(RootDir)%(Directory)%(Filename).pdb')" />
			<_SourceGeneratorSharedPackageFile Include="@(_SourceGeneratorSharedAssembly->'%(RootDir)%(Directory)%(Filename).xml')" />

			<TfmSpecificPackageFile
				Include="@(_SourceGeneratorSharedPackageFile)"
				Condition="Exists('%(_SourceGeneratorSharedPackageFile.Identity)')"
			>
				<PackagePath>lib/$(TargetFramework)/</PackagePath>
			</TfmSpecificPackageFile>
		</ItemGroup>
	</Target>
</Project>
