using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Purview.SourceGeneratorFramework.Examples;

/// <summary>
/// Emits the <c>GenerateCodeWriterSampleAttribute</c> and the sample class generated by
/// <see cref="CodeWriterSampleGenerator"/>, demonstrating the structured <see cref="CodeWriter"/> API.
/// </summary>
static class CodeWriterSampleEmitter
{
	/// <summary>
	/// Emits the <c>GenerateCodeWriterSampleAttribute</c> marker attribute.
	/// </summary>
	public static void EmitAttribute(IncrementalGeneratorPostInitializationContext spc)
	{
		CodeWriter writer = new(GenerationSettings.Create<CodeWriterSampleGenerator>(), throwOnUnclosedScopes: false);

		writer.AutoGeneratedHeader();
		writer.FileScopedNamespace(TypeLibrary.GenerateCodeWriterSampleAttribute);

		writer.AttributeClass(
			TypeLibrary.GenerateCodeWriterSampleAttribute.Name,
			TypeDeclarationAccessibility.Public,
			AttributeTargets.Class,
			_ => { },
			configure: options => options with { IsPartial = false }
		);

		spc.AddSource("GenerateCodeWriterSampleAttribute.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
	}

	/// <summary>
	/// Emits the sample class demonstrating the minimal overloads, scoped declarations, structured
	/// statements, and <see cref="CodeWriter.NetConditionalReturn"/>.
	/// </summary>
	public static void Execute(SourceProductionContext spc, CodeWriterSampleTarget target)
	{
		if (string.IsNullOrWhiteSpace(target.TypeName))
			return;

		CodeWriter writer = new(GenerationSettings.Create<CodeWriterSampleGenerator>(), throwOnUnclosedScopes: false);

		writer.AutoGeneratedHeader();
		writer.PragmaDisable("CS8625");
		writer.FileScopedNamespace(target.Namespace ?? "Purview.SourceGeneratorFramework.Examples.Samples");

		writer.Comment("Generated by the CodeWriter sample generator.");

		writer.Class(
			target.TypeName + "CodeWriterSample",
			TypeDeclarationAccessibility.Public,
			options => options with { IsSealed = true, IsPartial = false },
			body =>
			{
				body.Field(
					"_value",
					TypeIdentity.Create<int>().AsTypeReference(),
					TypeDeclarationAccessibility.Private,
					options => options with { IsReadOnly = true }
				);

				body.Constructor(
					target.TypeName + "CodeWriterSample",
					TypeDeclarationAccessibility.Public,
					options =>
						options with
						{
							Parameters = [new("value", TypeIdentity.Create<int>().AsTypeReference())],
						},
					constructorBody => constructorBody.Assignment("_value", "value")
				);

				body.Property(
					"Value",
					TypeIdentity.Create<int>().AsTypeReference(),
					TypeDeclarationAccessibility.Public,
					options => options with { HasGetter = true }
				);

				// The accessibility is omitted, so the writer's default (public) is applied.
				body.Property("DefaultAccessibility", TypeIdentity.Create<string>().AsTypeReference());

				body.HashDefines(
					"NET",
					conditional => conditional.Comment("This member is emitted only for .NET targets.")
				);

				using (body.OpenPragmasScope("CS0618"))
				{
					body.Comment("Emitted with the warning suppressed.");
				}

				body.Method(
					"Describe",
					TypeIdentity.Create<string>().AsTypeReference(),
					TypeDeclarationAccessibility.Public,
					options =>
						options with
						{
							IsStatic = true,
							Parameters = [new("value", TypeIdentity.Create<int>().AsTypeReference())],
						},
					methodBody =>
					{
						methodBody.MethodCall("global::System.Console.WriteLine", "\"Describe\"");
						methodBody.Return("value.ToString()");
					}
				);

				using (
					body.MethodScope(
						"Format",
						TypeIdentity.Create<string>().AsTypeReference(),
						TypeDeclarationAccessibility.Public
					)
				)
					body.NetConditionalReturn("Value: {_value}");
			}
		);

		spc.AddSource($"{target.TypeName}.CodeWriterSample.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
	}
}
