using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Purview.SourceGeneratorFramework.Examples;

/// <summary>
/// Emits source generated by the <see cref="ServiceRegistrationGenerator"/>.
/// </summary>
static class ServiceRegistrationEmitter
{
	/// <summary>
	/// Emits the <c>GenerateServiceAttribute</c> attribute and <c>ServiceLifetime</c> enum
	/// via <see cref="CodeWriter"/>.
	/// </summary>
	public static void EmitAttributeAndEnum(
		IncrementalGeneratorPostInitializationContext spc,
		string generatorName,
		string? generatorVersion
	)
	{
		var writer = new CodeWriter(
			generatorName: generatorName,
			generatorVersion: generatorVersion ?? "1.0.0.0",
			throwOnUnclosedScopes: false
		);

		writer.WriteAutoGeneratedHeader();
		writer.WriteFileScopedNamespace(ServiceRegistrationGeneratorTypeLibrary.GenerateServiceAttribute);

		writer.WriteEnum(
			new TypeDeclarationOptions(ServiceRegistrationGeneratorTypeLibrary.ServiceLifetime)
			{
				Accessibility = TypeDeclarationAccessibility.Public,
				IsPartial = false,
			},
			ew =>
			{
				ew.WriteLine("Singleton = 0,");
				ew.WriteLine("Scoped = 1,");
				ew.WriteLine("Transient = 2,");
			}
		);

		writer.WriteAttributeClass(
			new TypeDeclarationOptions(ServiceRegistrationGeneratorTypeLibrary.GenerateServiceAttribute)
			{
				Accessibility = TypeDeclarationAccessibility.Public,
				IsPartial = false,
			},
			AttributeTargets.Class,
			cw =>
			{
				cw.WriteConstructor(
					new ConstructorDeclarationOptions("GenerateServiceAttribute")
					{
						Accessibility = TypeDeclarationAccessibility.Public,
						Parameters =
						[
							new ParameterDeclarationOptions(
								"lifetime",
								ServiceRegistrationGeneratorTypeLibrary.ServiceLifetime
							)
							{
								DefaultValue = "ServiceLifetime.Singleton",
							},
						],
					},
					_ => { }
				);

				cw.WriteProperty(
					new PropertyDeclarationOptions("Lifetime", ServiceRegistrationGeneratorTypeLibrary.ServiceLifetime)
					{
						Accessibility = TypeDeclarationAccessibility.Public,
						Initializer = "lifetime",
					}
				);

				cw.WriteProperty(
					new PropertyDeclarationOptions("Name", "string?")
					{
						Accessibility = TypeDeclarationAccessibility.Public,
						HasSetter = true,
						Initializer = "null",
					}
				);
			}
		);

		spc.AddSource("GenerateServiceAttribute.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
	}

	/// <summary>
	/// Emits the <c>ServiceCollectionExtensions</c> class and, optionally, the <c>ServiceInfo</c> class.
	/// </summary>
	public static void Execute(
		SourceProductionContext spc,
		ServiceRegistrationGenerationModel model,
		ISourceGenLogger? logger
	)
	{
		if (model.IsDisabled)
		{
			logger?.Info("ServiceRegistrationGenerator is disabled.");
			return;
		}

		if (model.Targets.IsEmpty)
		{
			logger?.Info("No service targets found.");
			return;
		}

		var writer = model.Context.CreateCodeWriter();
		writer.WriteAutoGeneratedHeader();
		writer.WriteFileScopedNamespace(ServiceRegistrationGeneratorTypeLibrary.ServiceCollectionExtensions);

		writer.WriteClass(
			new TypeDeclarationOptions(ServiceRegistrationGeneratorTypeLibrary.ServiceCollectionExtensions)
			{
				Accessibility = TypeDeclarationAccessibility.Public,
				IsStatic = true,
				IsPartial = false,
			},
			cw =>
				cw.WriteMethod(
					new MethodDeclarationOptions(
						"AddExampleServices",
						ServiceRegistrationGeneratorTypeLibrary
							.Microsoft
							.Extensions
							.DependencyInjection
							.IServiceCollection
					)
					{
						Accessibility = TypeDeclarationAccessibility.Public,
						IsStatic = true,
						Parameters =
						[
							new ParameterDeclarationOptions(
								"services",
								ServiceRegistrationGeneratorTypeLibrary
									.Microsoft
									.Extensions
									.DependencyInjection
									.IServiceCollection
							)
							{
								IsThis = true,
							},
						],
					},
					body =>
					{
						foreach (var target in model.Targets)
						{
							body.Comment($"Service name: {target.Name}");
							body.WriteLine(
								$"{ServiceRegistrationGeneratorTypeLibrary.Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions}.Add{target.LifetimeMemberName}<{target.TypeName}>(services);"
							);
						}

						body.WriteLine("return services;");
					}
				)
		);

		spc.AddSource("ServiceCollectionExtensions.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));

		if (model.EmitServiceInfo)
			EmitServiceInfo(spc, model);
	}

	static void EmitServiceInfo(SourceProductionContext spc, ServiceRegistrationGenerationModel model)
	{
		var writer = model.Context.CreateCodeWriter();
		writer.WriteAutoGeneratedHeader();
		writer.WriteFileScopedNamespace(ServiceRegistrationGeneratorTypeLibrary.ServiceInfo);

		writer.WriteClass(
			new TypeDeclarationOptions(ServiceRegistrationGeneratorTypeLibrary.ServiceInfo)
			{
				Accessibility = TypeDeclarationAccessibility.Public,
				IsStatic = true,
				IsPartial = false,
			},
			cw =>
			{
				foreach (var target in model.Targets)
				{
					cw.WriteClass(
						new TypeDeclarationOptions(target.ClassName)
						{
							Accessibility = TypeDeclarationAccessibility.Public,
							IsStatic = true,
							IsPartial = false,
						},
						inner =>
						{
							inner.WriteProperty(
								new PropertyDeclarationOptions("Name", TypeValueObject.Create<string>())
								{
									Accessibility = TypeDeclarationAccessibility.Public,
									IsStatic = true,
									ExpressionBody = $"\"{target.Name}\"",
								}
							);

							inner.WriteProperty(
								new PropertyDeclarationOptions("Lifetime", TypeValueObject.Create<string>())
								{
									Accessibility = TypeDeclarationAccessibility.Public,
									IsStatic = true,
									ExpressionBody = $"\"{target.LifetimeMemberName}\"",
								}
							);

							inner.WriteProperty(
								new PropertyDeclarationOptions("Type", PurviewTypeLibrary.System.Type)
								{
									Accessibility = TypeDeclarationAccessibility.Public,
									IsStatic = true,
									ExpressionBody = $"typeof({target.TypeName})",
								}
							);
						}
					);
				}
			}
		);

		spc.AddSource("ServiceInfo.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
	}
}
