using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace Purview.SourceGeneratorFramework.Examples;

/// <summary>
/// Emits source generated by the <see cref="ServiceRegistrationGenerator"/>.
/// </summary>
static class ServiceRegistrationEmitter
{
	/// <summary>
	/// Emits the <c>GenerateServiceAttribute</c> attribute and <c>ServiceLifetime</c> enum
	/// via <see cref="CodeWriter"/>.
	/// </summary>
	public static void EmitAttributeAndEnum(IncrementalGeneratorPostInitializationContext spc)
	{
		CodeWriter writer = new(
			GenerationSettings.Create<ServiceRegistrationGenerator>(),
			throwOnUnclosedScopes: false
		);

		writer.WriteAutoGeneratedHeader();
		writer.WriteFileScopedNamespace(TypeLibrary.GenerateServiceAttribute);

		writer.WriteEnum(
			new(TypeLibrary.ServiceLifetime, TypeDeclarationAccessibility.Public) { IsPartial = false },
			ew =>
			{
				ew.WriteLine("Singleton = 0,");
				ew.WriteLine("Scoped = 1,");
				ew.WriteLine("Transient = 2,");
			}
		);

		writer.WriteAttributeClass(
			new(TypeLibrary.GenerateServiceAttribute, TypeDeclarationAccessibility.Public) { IsPartial = false },
			AttributeTargets.Class,
			cw =>
			{
				cw.WriteConstructor(
					new("GenerateServiceAttribute", TypeDeclarationAccessibility.Public)
					{
						Parameters =
						[
							new("lifetime", TypeLibrary.ServiceLifetime) { DefaultValue = "ServiceLifetime.Singleton" },
						],
					},
					body => body.WriteLine("Lifetime = lifetime;")
				);

				cw.WriteProperty(new("Lifetime", TypeLibrary.ServiceLifetime, TypeDeclarationAccessibility.Public));

				cw.WriteProperty(
					new("Name", PurviewTypeLibrary.System.String.MakeNullable(), TypeDeclarationAccessibility.Public)
					{
						HasSetter = true,
						Initializer = "null",
					}
				);
			}
		);

		spc.AddSource("GenerateServiceAttribute.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
	}

	/// <summary>
	/// Emits the <c>ServiceCollectionExtensions</c> class and, optionally, the <c>ServiceInfo</c> class.
	/// </summary>
	public static void Execute(SourceProductionContext spc, ServiceRegistrationGenerationModel model)
	{
		if (model.Context.Settings.IsSourceGeneratorDisabled)
		{
			model.Context.Info("ServiceRegistrationGenerator is disabled.");
			return;
		}

		if (model.Targets.IsEmpty)
		{
			model.Context.Info("No service targets found.");
			return;
		}

		var writer = model.Context.CreateCodeWriter();
		writer.WriteAutoGeneratedHeader();
		writer.WriteFileScopedNamespace(TypeLibrary.ServiceCollectionExtensions);

		writer.WriteClass(
			new(TypeLibrary.ServiceCollectionExtensions, TypeDeclarationAccessibility.Public)
			{
				IsStatic = true,
				IsPartial = false,
			},
			cw =>
				cw.WriteMethod(
					new(
						"AddExampleServices",
						TypeLibrary.Microsoft.Extensions.DependencyInjection.IServiceCollection,
						TypeDeclarationAccessibility.Public
					)
					{
						IsStatic = true,
						Parameters =
						[
							new("services", TypeLibrary.Microsoft.Extensions.DependencyInjection.IServiceCollection)
							{
								IsThis = true,
							},
						],
					},
					body =>
					{
						foreach (var target in model.Targets)
						{
							body.Comment($"Service name: {target.Name}");
							body.WriteLine(
								$"{TypeLibrary.Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions}.Add{target.LifetimeMemberName}<{target.TypeName}>(services);"
							);
						}

						body.WriteLine("return services;");
					}
				)
		);

		spc.AddSource("ServiceCollectionExtensions.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));

		if (model.EmitServiceInfo)
			EmitServiceInfo(spc, model);
	}

	static void EmitServiceInfo(SourceProductionContext spc, ServiceRegistrationGenerationModel model)
	{
		var writer = model.Context.CreateCodeWriter();
		writer.WriteAutoGeneratedHeader();
		writer.WriteFileScopedNamespace(TypeLibrary.ServiceInfo);

		writer.WriteClass(
			new(TypeLibrary.ServiceInfo, TypeDeclarationAccessibility.Public) { IsStatic = true, IsPartial = false },
			cw =>
			{
				foreach (var target in model.Targets)
				{
					cw.WriteClass(
						new(target.ClassName)
						{
							Accessibility = TypeDeclarationAccessibility.Public,
							IsStatic = true,
							IsPartial = false,
						},
						inner =>
						{
							inner.WriteProperty(
								new(
									"Name",
									TypeIdentity.Create<string>().AsTypeReference(),
									TypeDeclarationAccessibility.Public
								)
								{
									IsStatic = true,
									ExpressionBody = $"\"{target.Name}\"",
								}
							);

							inner.WriteProperty(
								new(
									"Lifetime",
									TypeIdentity.Create<string>().AsTypeReference(),
									TypeDeclarationAccessibility.Public
								)
								{
									IsStatic = true,
									ExpressionBody = $"\"{target.LifetimeMemberName}\"",
								}
							);

							inner.WriteProperty(
								new("Type", PurviewTypeLibrary.System.Type, TypeDeclarationAccessibility.Public)
								{
									IsStatic = true,
									ExpressionBody = $"typeof({target.TypeName})",
								}
							);
						}
					);
				}
			}
		);

		spc.AddSource("ServiceInfo.g.cs", SourceText.From(writer.ToString(), Encoding.UTF8));
	}
}
