<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks></TargetFrameworks>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<IsRoslynComponent>true</IsRoslynComponent>
		<NoWarn>$(NoWarn);CS1591;RS2008;</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SourceGeneratorFramework\SourceGeneratorFramework.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
	</ItemGroup>
</Project>
