using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Purview.SourceGeneratorFramework.Helpers;
using Purview.SourceGeneratorFramework.Models;

namespace Purview.SourceGeneratorFramework.ExampleGenerator;

[Generator]
public sealed class TypeInfoGenerator : IIncrementalGenerator
{
	const string AttributeName = "GenerateTypeInfoAttribute";
	const string AttributeNamespace = "Purview.SourceGeneratorFramework.Examples";
	static readonly TypeValueObject AttributeType = new(AttributeName, AttributeNamespace);

	static readonly DiagnosticDescriptor NotPartialDescriptor = new(
		"EXG0001",
		"Type must be partial",
		"Type '{0}' must be partial to receive generated type info",
		"TypeInfoGenerator",
		DiagnosticSeverity.Error,
		true
	);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static spc =>
			spc.AddSource(
				"GenerateTypeInfoAttribute.g.cs",
				"""
				namespace Purview.SourceGeneratorFramework.Examples
				{
					[System.AttributeUsage(System.AttributeTargets.Class)]
					public sealed class GenerateTypeInfoAttribute : System.Attribute { }
				}
				"""
			)
		);

		var typeInfos = IncrementalPipeline.ForAttributeWithMetadataName(
			context,
			AttributeType,
			static (ctx, ct) =>
			{
				var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.TargetNode, ct);
				var typeDeclaration = (TypeDeclarationSyntax)ctx.TargetNode;
				var @namespace =
					symbol?.ContainingNamespace?.IsGlobalNamespace == true
						? string.Empty
						: symbol?.ContainingNamespace?.ToDisplayString() ?? string.Empty;

				return new TypeInfoTarget(
					symbol?.Name ?? "Unknown",
					@namespace,
					TypeHelpers.IsPartial(typeDeclaration),
					symbol is not null
						? TypeHelpers.ToFullyQualifiedDisplayString(symbol)
						: string.Empty
				);
			}
		);

		context.RegisterSourceOutput(
			typeInfos.Collect(),
			static (spc, targets) =>
			{
				foreach (var target in targets.Distinct())
				{
					if (!target.IsPartial)
					{
						spc.ReportDiagnostic(
							Diagnostic.Create(NotPartialDescriptor, Location.None, target.Name)
						);
						continue;
					}

					GenerateTypeInfo(spc, target);
				}
			}
		);
	}

	static void GenerateTypeInfo(SourceProductionContext spc, TypeInfoTarget target)
	{
		var writer = new CodeWriter();
		writer.WriteAutoGeneratedHeader(nameof(TypeInfoGenerator));
		writer.WriteUsing("System");

		if (string.IsNullOrEmpty(target.Namespace))
		{
			WriteTypeInfoClass(writer, target);
		}
		else
		{
			using (writer.WriteBlockNamespaceScope(target.Namespace))
				WriteTypeInfoClass(writer, target);
		}

		spc.AddSource($"{target.Name}.TypeInfo.g.cs", writer.ToString());
	}

	static void WriteTypeInfoClass(CodeWriter writer, TypeInfoTarget target)
	{
		using (
			writer.WriteClassScope(
				new TypeDeclarationOptions(target.Name)
				{
					Accessibility = TypeDeclarationAccessibility.Public,
					IsStatic = true,
				}
			)
		)
		{
			using (
				writer.WriteClassScope(
					new TypeDeclarationOptions("TypeInfo")
					{
						Accessibility = TypeDeclarationAccessibility.Public,
						IsStatic = true,
						IsPartial = false,
					}
				)
			)
			{
				writer.WriteLine($"public const string Name = \"{target.Name}\";");
				writer.WriteLine($"public const string FullName = \"{target.FullName}\";");
				writer.WriteLine($"public const string Namespace = \"{target.Namespace}\";");
			}
		}
	}

	readonly struct TypeInfoTarget(string name, string @namespace, bool isPartial, string fullName)
		: IEquatable<TypeInfoTarget>
	{
		public string Name { get; } = name;

		public string Namespace { get; } = @namespace;

		public bool IsPartial { get; } = isPartial;

		public string FullName { get; } = fullName;

		public bool Equals(TypeInfoTarget other) =>
			Name == other.Name
			&& Namespace == other.Namespace
			&& IsPartial == other.IsPartial
			&& FullName == other.FullName;

		public override bool Equals(object? obj) => obj is TypeInfoTarget other && Equals(other);

		public override int GetHashCode() =>
			Name.GetHashCode()
			^ Namespace.GetHashCode()
			^ IsPartial.GetHashCode()
			^ FullName.GetHashCode();
	}
}
