using Purview.SourceGeneratorFramework.Logging;

namespace Purview.SourceGeneratorFramework;

/// <summary>
/// Provides execution services for source generation, including the compilation, immutable
/// settings, optional logging, and symbol-resolution helpers.
/// </summary>
/// <remarks>
/// Initializes a generation context.
/// </remarks>
public sealed class GenerationContext<TCapabilities>(
	TCapabilities Capabilities,
	GenerationSettings Settings,
	ISourceGenLogger? Logger = null
) : ISourceGenLogger, IEqualityComparer<GenerationContext<TCapabilities>>, IEquatable<GenerationContext<TCapabilities>>
	where TCapabilities : class, IGenerationCapabilities
{
	/// <summary>
	/// Gets the capabilities of the source generator, which are used to determine what features are available during generation.
	/// </summary>
	public TCapabilities Capabilities { get; } = Capabilities ?? throw new ArgumentNullException(nameof(Capabilities));

	/// <summary>
	/// Gets the immutable generation settings.
	/// </summary>
	public GenerationSettings Settings { get; } = Settings ?? throw new ArgumentNullException(nameof(Settings));

	/// <summary>
	/// Gets the optional logger. This is primarily used during source generator test execution, such as
	/// unit or integration tests, to capture and assert on log messages generated by the source generator.
	/// </summary>
	public ISourceGenLogger? Logger { get; } = Logger;

	/// <summary>
	/// Creates a new independently owned code writer.
	/// </summary>
	public CodeWriter CreateCodeWriter() => new(Settings, throwOnUnclosedScopes: Settings.ValidateCodeWriterScopes);

	/// <inheritdoc />
	public void Log(SourceGenLogLevel level, int indentation, string message, params object[] args) =>
		Logger?.Log(level, indentation, message, args);

	/// <inheritdoc cref="IEquatable{T}.Equals(T)" />
	public bool Equals(GenerationContext<TCapabilities>? other) => Equals(this, other);

	/// <inheritdoc />
	public override bool Equals(object? obj) => obj is GenerationContext<TCapabilities> other && Equals(other);

	/// <inheritdoc />
	public bool Equals(GenerationContext<TCapabilities>? x, GenerationContext<TCapabilities>? y) =>
		ReferenceEquals(x, y)
		|| (
			x is not null
			&& y is not null
			&& EqualityComparer<TCapabilities>.Default.Equals(x.Capabilities, y.Capabilities)
			&& EqualityComparer<GenerationSettings>.Default.Equals(x.Settings, y.Settings)
		);

	/// <inheritdoc />
	public override int GetHashCode()
	{
		unchecked
		{
			var hash = 17;
			hash = (hash * 31) + EqualityComparer<TCapabilities>.Default.GetHashCode(Capabilities);
			hash = (hash * 31) + EqualityComparer<GenerationSettings>.Default.GetHashCode(Settings);
			return hash;
		}
	}

	/// <inheritdoc />
	public int GetHashCode(GenerationContext<TCapabilities> obj) => obj?.GetHashCode() ?? 0;
}

/// <summary>
/// Represents an empty capabilities type that can be used when no specific capabilities are required for a source generator.
/// </summary>
public sealed record EmptyCapabilities : IGenerationCapabilities
{
	/// <summary>
	/// Gets the singleton instance of <see cref="EmptyCapabilities"/>. This instance can be used when no specific capabilities are required for a source generator.
	/// </summary>
	public static readonly EmptyCapabilities Instance = new();
}
