namespace Purview.SourceGeneratorFramework;

/// <summary>
/// Controls whether the <c>#nullable enable</c> directive is emitted by <c>WriteAutoGeneratedHeader</c>
/// and whether nullable reference annotations are rendered by type writing. Both stay in lockstep.
/// </summary>
public enum NullableDirectiveMode
{
	/// <summary>
	/// Detects whether the target compilation has nullable annotations enabled and emits the
	/// <c>#nullable enable</c> directive only when it does. When the compilation state is unknown,
	/// the directive is emitted to preserve existing behavior.
	/// </summary>
	Auto = 0,

	/// <summary>
	/// Always emits the <c>#nullable enable</c> directive.
	/// </summary>
	Always = 1,

	/// <summary>
	/// Never emits the <c>#nullable enable</c> directive.
	/// </summary>
	Disable = 2,
}
