<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks></TargetFrameworks>
		<TargetFramework>netstandard2.0</TargetFramework>
		<DisableSourceLink>true</DisableSourceLink>
		<AssemblyName>$(NamespacePrefix).Shared</AssemblyName>
		<RootNamespace>$(NamespacePrefix)</RootNamespace>
		<IsPackable>false</IsPackable>
		<PackageId>$(NamespacePrefix).Shared</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
	</ItemGroup>
</Project>
