using Microsoft.CodeAnalysis;
using Purview.SourceGeneratorFramework.Helpers;

namespace Purview.SourceGeneratorFramework.TestGenerators;

/// <summary>
/// Mirrors a downstream generator that opts into nullable annotations regardless of the consuming
/// compilation by passing explicit settings with <see cref="NullableDirectiveMode.Always"/> through
/// the settings-based pipeline overload.
/// </summary>
public sealed class AlwaysNullableContextTestGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var settings = GenerationSettings.Create<AlwaysNullableContextTestGenerator>() with
		{
			NullableDirectiveMode = NullableDirectiveMode.Always,
		};

		var generationContext = IncrementalPipeline.GenerationContextValueProvider(
			context,
			settings,
			static (_, _, _, _) => EmptyCapabilities.Instance
		);

		context.RegisterSourceOutput(
			generationContext,
			static (spc, ctx) =>
			{
				var writer = ctx.CreateCodeWriter();
				writer.WriteAutoGeneratedHeader();
				writer.WriteFileScopedNamespace("Test");
				writer.WriteClass(
					new TypeDeclarationOptions("Sample") { Accessibility = TypeDeclarationAccessibility.Public },
					body =>
						body.WriteProperty(
							new(
								"Name",
								TypeIdentity.Create<string>().MakeNullable(writer),
								TypeDeclarationAccessibility.Public
							)
						)
				);

				spc.AddSource("AlwaysNullableContext.g.cs", writer.ToString());
			}
		);
	}
}
