using Microsoft.CodeAnalysis;
using Purview.SourceGeneratorFramework.Helpers;

namespace Purview.SourceGeneratorFramework.TestGenerators;

/// <summary>
/// Emits a generated file whose header and nullable reference annotation are driven by an explicit
/// <see cref="GenerationSettings.IsNullableContextEnabled"/> value, proving that a configured value
/// takes precedence over the compilation's nullable context.
/// </summary>
public sealed class ExplicitNullableContextTestGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var generationContext = IncrementalPipeline.DefaultGenerationContextValueProvider(
			context,
			new GenerationSettings("ExplicitNullableContextTestGenerator", "1.0.0") { IsNullableContextEnabled = true }
		);

		context.RegisterSourceOutput(
			generationContext,
			static (spc, ctx) =>
			{
				var writer = ctx.CreateCodeWriter();
				writer.WriteAutoGeneratedHeader();
				writer.WriteFileScopedNamespace("Test");
				writer.WriteClass(
					new TypeDeclarationOptions("Sample") { Accessibility = TypeDeclarationAccessibility.Public },
					body =>
						body.WriteProperty(
							new(
								"Name",
								TypeIdentity.Create<string>().MakeNullable(writer),
								TypeDeclarationAccessibility.Public
							)
						)
				);

				spc.AddSource("ExplicitNullableContext.g.cs", writer.ToString());
			}
		);
	}
}
