using Microsoft.CodeAnalysis;
using Purview.SourceGeneratorFramework.Helpers;

namespace Purview.SourceGeneratorFramework.TestGenerators;

/// <summary>
/// Emits a generated file whose header and nullable reference annotation are derived from the
/// compilation's nullable context through the pipeline-resolved settings.
/// </summary>
public sealed class NullableContextTestGenerator : IIncrementalGenerator
{
	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var generationContext = IncrementalPipeline.DefaultGenerationContextValueProvider(
			context,
			new GenerationSettings("NullableContextTestGenerator", "1.0.0")
		);

		context.RegisterSourceOutput(
			generationContext,
			static (spc, ctx) =>
			{
				var writer = ctx.CreateCodeWriter();
				writer.AutoGeneratedHeader();
				writer.FileScopedNamespace("Test");
				writer.Class(
					new TypeDeclarationOptions("Sample") { Accessibility = TypeDeclarationAccessibility.Public },
					body =>
						body.Property(
							new(
								"Name",
								TypeIdentity.Create<string>().MakeNullable(writer),
								TypeDeclarationAccessibility.Public
							)
						)
				);

				spc.AddSource("NullableContext.g.cs", writer.ToString());
			}
		);
	}
}
