using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Purview.SourceGeneratorFramework.Helpers;

/// <summary>
/// Provides extension methods for <see cref="IncrementalGeneratorInitializationContext"/>.
/// </summary>
public static class IncrementalGeneratorInitializationContextExtensions
{
	/// <summary>
	/// Registers the <c>Microsoft.CodeAnalysis.EmbeddedAttribute</c> source using a <see cref="CodeWriter"/>.
	/// </summary>
	/// <param name="context">The initialization context.</param>
	/// <param name="generatorName">The generator name to stamp into the generated source.</param>
	/// <param name="generatorVersion">The optional generator version.</param>
	/// <param name="fileName">The source file name.</param>
	public static void RegisterEmbeddedAttribute(
		this IncrementalGeneratorInitializationContext context,
		string generatorName,
		string? generatorVersion = null,
		string fileName = "EmbeddedAttribute.g.cs"
	)
	{
		if (string.IsNullOrWhiteSpace(generatorName))
			throw new ArgumentException("Generator name cannot be null or whitespace.", nameof(generatorName));

		context.RegisterPostInitializationOutput(spc =>
		{
			var writer = new CodeWriter(generatorName, generatorVersion ?? "1.0.0.0");
			writer.WriteAutoGeneratedHeader();
			writer.WriteFileScopedNamespace(PurviewTypeLibrary.Microsoft.CodeAnalysis.EmbeddedAttribute);

			// The compiler treats this special type as implicitly compiler-generated and embedded,
			// so no generated attributes are applied here.
			writer.WriteClass(
				new("EmbeddedAttribute")
				{
					IsSealed = true,
					IsPartial = true,
					BaseType = PurviewTypeLibrary.System.Attribute,
					IncludeGeneratedAttributes = false,
				},
				bodyWriter =>
					bodyWriter.Comment(
						"This is a special type that is treated as implicitly compiler-generated and embedded by the compiler."
					)
			);

			spc.AddSource(fileName, SourceText.From(writer.ToString(), Encoding.UTF8));
		});
	}
}
