// <auto-generated />

namespace Purview.SourceGeneratorFramework.Generators;

#nullable enable

/// <summary>Generates parsing members for an attribute-data model.</summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
[global::Microsoft.CodeAnalysis.Embedded]
sealed class GenerateAttribute : global::System.Attribute
{
	/// <summary>Initializes the attribute for the target attribute type.</summary>
	public GenerateAttribute(global::System.Type targetAttribute)
	{
		TargetAttribute =
			targetAttribute ?? throw new global::System.ArgumentNullException(nameof(targetAttribute));
	}

	/// <summary>Initializes the attribute for the target attribute type name.</summary>
	public GenerateAttribute(string targetAttribute)
	{
		TargetAttributeName =
			targetAttribute ?? throw new global::System.ArgumentNullException(nameof(targetAttribute));
	}

	/// <summary>Gets the attribute type represented by the generated model.</summary>
	public global::System.Type? TargetAttribute { get; }

	/// <summary>Gets the attribute type name represented by the generated model.</summary>
	public string? TargetAttributeName { get; }

	/// <summary>Gets or sets whether derived attribute types are accepted.</summary>
	public bool MatchByInheritance { get; set; }

	/// <summary>Gets or sets whether constructor and named properties are discovered automatically.</summary>
	public bool AutoDiscover { get; set; }
}

/// <summary>Marks a record parameter as a named attribute argument.</summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
[global::Microsoft.CodeAnalysis.Embedded]
sealed class PropertyAttribute : global::System.Attribute
{
	/// <summary>Initializes a new instance of the <see cref="PropertyAttribute"/> class.</summary>
	public PropertyAttribute() { }

	/// <summary>Gets or sets an optional named-property mapping.</summary>
	public string? Name { get; set; }

	/// <summary>Gets or sets the value used when the named argument is not specified.</summary>
	public object? DefaultValue { get; set; }

	/// <summary>Gets or sets a value indicating whether the property represents an enum whose type is not known to the generator.</summary>
	public bool IsEnum { get; set; }
}

/// <summary>Marks a record parameter as a constructor argument.</summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
[global::Microsoft.CodeAnalysis.Embedded]
sealed class ArgumentAttribute : global::System.Attribute
{
	/// <summary>Initializes a new instance of the <see cref="ArgumentAttribute"/> class.</summary>
	public ArgumentAttribute() { }

	/// <summary>Initializes a new instance of the <see cref="ArgumentAttribute"/> class.</summary>
	/// <param name="name">The constructor parameter name.</param>
	public ArgumentAttribute(string name)
	{
		Name = name;
	}

	/// <summary>Initializes a new instance of the <see cref="ArgumentAttribute"/> class.</summary>
	/// <param name="index">The constructor argument index.</param>
	public ArgumentAttribute(int index)
	{
		Index = index;
	}

	/// <summary>Gets or sets the constructor parameter name.</summary>
	public string? Name { get; set; }

	/// <summary>Gets or sets the constructor argument index.</summary>
	public int Index { get; set; } = -1;

	/// <summary>Gets or sets the value used when the constructor argument is not specified.</summary>
	public object? DefaultValue { get; set; }

	/// <summary>Gets or sets a value indicating whether the argument represents an enum whose type is not known to the generator.</summary>
	public bool IsEnum { get; set; }
}

/// <summary>Marks a record parameter as a nested generated attribute-data model.</summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
[global::Microsoft.CodeAnalysis.Embedded]
sealed class NestedModelAttribute : global::System.Attribute
{
}

/// <summary>Excludes a record parameter from the generated attribute-data model.</summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
[global::Microsoft.CodeAnalysis.Embedded]
sealed class ExcludeAttribute : global::System.Attribute
{
}

/// <summary>Marks a record parameter as a generic type argument of the attribute class.</summary>
[global::System.AttributeUsage(global::System.AttributeTargets.Parameter, AllowMultiple = false, Inherited = false)]
[global::Microsoft.CodeAnalysis.Embedded]
sealed class GenericTypeArgumentAttribute : global::System.Attribute
{
	/// <summary>Initializes a new instance marking the first type argument.</summary>
	public GenericTypeArgumentAttribute() { }

	/// <summary>Initializes a new instance marking the type argument at the specified index.</summary>
	public GenericTypeArgumentAttribute(int index)
	{
		Index = index;
	}

	/// <summary>Initializes a new instance marking the type argument with the specified type parameter name.</summary>
	public GenericTypeArgumentAttribute(string name)
	{
		Name = name;
	}

	/// <summary>Gets or sets the type parameter name.</summary>
	public string? Name { get; set; }

	/// <summary>Gets or sets the type argument index.</summary>
	public int Index { get; set; } = -1;
}
