using Microsoft.CodeAnalysis.Text;

namespace Purview.SourceGeneratorFramework.Generators.Model;

static partial class SourceEmitter
{
	public static IEnumerable<(string HintName, SourceText Source)> AttributeDataEmit()
	{
		yield return (GetHintName(nameof(GenerateAttribute)), GenerateAttribute());
		yield return (GetHintName(nameof(PropertyAttribute)), PropertyAttribute());
		yield return (GetHintName(nameof(ArgumentAttribute)), ArgumentAttribute());
		yield return (GetHintName(nameof(NestedModelAttribute)), NestedModelAttribute());
		yield return (GetHintName(nameof(ExcludeAttribute)), ExcludeAttribute());
		yield return (GetHintName(nameof(GenericTypeArgumentAttribute)), GenericTypeArgumentAttribute());
	}

	static CodeWriter CreateWriter(string generatorName, TypeReference type)
	{
		CodeWriter writer = new(generatorName, AssemblyInfo.Version);

		return writer.WriteAutoGeneratedHeader().WriteFileScopedNamespace(type);
	}

	static string GetHintName(string name) => $"{name}.g.cs";
}
