using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace Purview.SourceGeneratorFramework.Testing.Generators;

[Generator]
public sealed class AttributeDataModelGenerator : IIncrementalGenerator, Abstractions.ILogSupport
{
	Abstractions.GenerationLogger? _logger;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(context =>
		{
			context.AddSource("EmbeddedAttribute.g.cs", SourceLibrary.EmbeddedAttributeSource);

			var attributeSource = EmbeddedResources.Load("AttributeDataModelAttributes");
			context.AddSource("AttributeDataModelAttributes.g.cs", attributeSource);
		});

		var targets = AttributeDataModelLibrary.GetTargets(context, _logger);

		context.RegisterSourceOutput(
			targets,
			static (spc, result) =>
			{
				if (result.HasDiagnostics)
					spc.ReportDiagnostics(result.Diagnostics);

				if (result.IsFatal || result.IsEmpty)
					return;

				GenerateAttributeDataModel(spc, result.Value!);
			}
		);
	}

	static void GenerateAttributeDataModel(
		SourceProductionContext spc,
		AttributeDataModelTarget target
	)
	{
		var writer = new CodeWriter();
		writer.WriteAutoGeneratedHeader(
			typeof(AttributeDataModelGenerator).FullName,
			AssemblyInfo.Version
		);
		writer.WriteUsing("System.Collections.Immutable");
		writer.WriteUsing("Microsoft.CodeAnalysis");
		writer.WriteUsing("Purview.SourceGeneratorFramework.Extensions");
		writer.WriteUsing("Purview.SourceGeneratorFramework.Helpers");
		writer.WriteUsing("Purview.SourceGeneratorFramework.Models");

		if (string.IsNullOrEmpty(target.Namespace))
		{
			WriteStruct(writer, target);
		}
		else
		{
			using (writer.WriteBlockNamespaceScope(target.Namespace))
				WriteStruct(writer, target);
		}

		spc.AddSource($"{target.StructName}.AttributeDataModel.g.cs", writer);
	}

	static void WriteStruct(CodeWriter writer, AttributeDataModelTarget target)
	{
		var options = new TypeDeclarationOptions(target.StructName)
		{
			Accessibility = target.Accessibility,
			IsReadOnly = true,
			IsPartial = true,
		};

		using (writer.WriteRecordStructScope(options))
		{
			writer.WriteProperty(
				new PropertyDeclarationOptions("Exists", "bool")
				{
					Accessibility = TypeDeclarationAccessibility.Public,
				}
			);
			foreach (var property in target.Properties)
			{
				if (property.IsExplicit)
					continue;

				writer.WriteProperty(
					new PropertyDeclarationOptions(
						property.PropertyName,
						property.FullyQualifiedTypeName
					)
					{
						Accessibility = TypeDeclarationAccessibility.Public,
						HasSetter = true,
						IsInitOnly = true,
					}
				);
			}
			WriteConstructor(writer, target);
			WriteTargetAttributeField(writer, target);
			WriteEmptyField(writer, target);
			WriteFromAttributeDataArrayMethod(writer, target);
			WriteFromAttributeDataArrayWithOutMethod(writer, target);
			WriteFromAttributeDataMethod(writer, target);
		}
	}

	static void WriteConstructor(CodeWriter writer, AttributeDataModelTarget target)
	{
		var parameters = ImmutableArray.CreateBuilder<ParameterDeclarationOptions>();
		parameters.Add(new ParameterDeclarationOptions("Exists", "bool"));
		foreach (var property in target.Properties)
		{
			parameters.Add(
				new ParameterDeclarationOptions(
					property.PropertyName,
					property.FullyQualifiedTypeName
				)
			);
		}

		writer.WriteConstructor(
			new ConstructorDeclarationOptions(target.StructName)
			{
				Accessibility = TypeDeclarationAccessibility.Public,
				Parameters = [.. parameters],
				Initializer = GetPrimaryConstructorInitializer(target),
			},
			body =>
			{
				body.WriteLine("this.Exists = Exists;");
				foreach (var property in target.Properties)
				{
					if (!property.IsExplicit)
						body.WriteLine($"this.{property.PropertyName} = {property.PropertyName};");
				}
			}
		);
	}

	static string? GetPrimaryConstructorInitializer(AttributeDataModelTarget target)
	{
		var arguments = target
			.Properties.Where(static property => property.IsExplicit)
			.Select(static property => property.PropertyName)
			.ToArray();

		return arguments.Length == 0 ? null : $"this({string.Join(", ", arguments)})";
	}

	static void WriteTargetAttributeField(CodeWriter writer, AttributeDataModelTarget target)
	{
		var namespaceValue = target.TargetAttribute.Namespace is null
			? "null"
			: $"\"{target.TargetAttribute.Namespace}\"";

		writer.WriteLine(
			$"static readonly global::Purview.SourceGeneratorFramework.Models.TypeValueObject TargetAttribute = new(\"{target.TargetAttribute.TypeName}\", {namespaceValue});"
		);
	}

	static void WriteEmptyField(CodeWriter writer, AttributeDataModelTarget target)
	{
		var values = new List<string> { "false" };
		foreach (var property in target.Properties)
		{
			values.Add(
				property.IsNonNullableReferenceType
					? $"default({property.FullyQualifiedTypeName})!"
					: $"default({property.FullyQualifiedTypeName})"
			);
		}

		writer.WriteLine(
			$"public static readonly {target.StructName} Empty = new({string.Join(", ", values)});"
		);
	}

	static void WriteFromAttributeDataArrayMethod(
		CodeWriter writer,
		AttributeDataModelTarget target
	)
	{
		var methodOptions = new MethodDeclarationOptions(
			"FromAttributeData",
			new TypeReferenceOptions(target.StructName)
		)
		{
			Accessibility = TypeDeclarationAccessibility.Public,
			IsStatic = true,
			Parameters =
			[
				new ParameterDeclarationOptions(
					"attributes",
					new TypeReferenceOptions(
						"global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.AttributeData>"
					)
				),
			],
		};

		writer.WriteMethod(
			methodOptions,
			w =>
			{
				w.WriteLine("for (var i = 0; i < attributes.Length; i++)");
				w.WriteBlock(
					null,
					body =>
					{
						body.WriteLine("var result = FromAttributeData(attributes[i]);");
						body.WriteLine("if (result.Exists)");
						body.WriteBlock(null, inner => inner.WriteLine("return result;"));
					}
				);
				w.WriteLine("return Empty;");
			}
		);
	}

	static void WriteFromAttributeDataArrayWithOutMethod(
		CodeWriter writer,
		AttributeDataModelTarget target
	)
	{
		var methodOptions = new MethodDeclarationOptions(
			"FromAttributeData",
			new TypeReferenceOptions(target.StructName)
		)
		{
			Accessibility = TypeDeclarationAccessibility.Public,
			IsStatic = true,
			Parameters =
			[
				new ParameterDeclarationOptions(
					"attributes",
					new TypeReferenceOptions(
						"global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.AttributeData>"
					)
				),
				new ParameterDeclarationOptions(
					"attribute",
					new TypeReferenceOptions("global::Microsoft.CodeAnalysis.AttributeData?")
				)
				{
					Modifier = ParameterModifier.Out,
				},
			],
		};

		writer.WriteMethod(
			methodOptions,
			w =>
			{
				w.WriteLine("attribute = null;");
				w.WriteLine("for (var i = 0; i < attributes.Length; i++)");
				w.WriteBlock(
					null,
					body =>
					{
						body.WriteLine("var result = FromAttributeData(attributes[i]);");
						body.WriteLine("if (result.Exists)");
						body.WriteBlock(
							null,
							inner =>
							{
								inner.WriteLine("attribute = attributes[i];");
								inner.WriteLine("return result;");
							}
						);
					}
				);
				w.WriteLine("return Empty;");
			}
		);
	}

	static void WriteFromAttributeDataMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		var methodOptions = new MethodDeclarationOptions(
			"FromAttributeData",
			new TypeReferenceOptions(target.StructName)
		)
		{
			Accessibility = TypeDeclarationAccessibility.Public,
			IsStatic = true,
			Parameters =
			[
				new ParameterDeclarationOptions(
					"attributeData",
					new TypeReferenceOptions("global::Microsoft.CodeAnalysis.AttributeData")
				),
			],
		};

		writer.WriteMethod(
			methodOptions,
			w =>
			{
				if (target.MatchByInheritance)
				{
					w.WriteLine(
						"if (attributeData.AttributeClass is null || (!TargetAttribute.Equals(attributeData.AttributeClass) && !global::Purview.SourceGeneratorFramework.Helpers.TypeHelpers.InheritsFrom(attributeData.AttributeClass, TargetAttribute)))"
					);
				}
				else
				{
					w.WriteLine("if (!TargetAttribute.Equals(attributeData.AttributeClass))");
				}
				w.WriteBlock(null, body => body.WriteLine("return Empty;"));

				foreach (var property in target.Properties)
				{
					WritePropertyExtraction(w, property);
				}

				var returnValues = new List<string> { "true" };
				foreach (var property in target.Properties)
				{
					var value = ToCamelCase(property.PropertyName);
					returnValues.Add(property.IsNonNullableReferenceType ? value + "!" : value);
				}

				w.WriteLine($"return new({string.Join(", ", returnValues)});");
			}
		);
	}

	static void WritePropertyExtraction(CodeWriter writer, AttributeDataModelProperty property)
	{
		var variableName = ToCamelCase(property.PropertyName);
		var typeName = GetNonNullableTypeName(property.FullyQualifiedTypeName);

		if (property.IsNestedModel)
		{
			writer.WriteLine(
				$"var {variableName} = {property.NestedModelTypeName}.FromAttributeData(attributeData);"
			);
			return;
		}

		var sources = property.Sources;
		if (sources.IsEmpty)
		{
			writer.WriteLine($"var {variableName} = default({typeName});");
			return;
		}

		if (sources.Length == 1)
		{
			var source = sources[0];
			if (property.HasDefaultValue)
			{
				WriteSingleSourceExtractionWithDefault(
					writer,
					source,
					variableName,
					typeName,
					property.DefaultValueExpression
				);
			}
			else
			{
				WriteSingleSourceExtraction(writer, source, variableName, typeName);
			}
			return;
		}

		WriteMultiSourceExtraction(
			writer,
			sources,
			variableName,
			typeName,
			property.HasDefaultValue,
			property.DefaultValueExpression
		);
	}

	static void WriteSingleSourceExtraction(
		CodeWriter writer,
		PropertySource source,
		string variableName,
		string typeName
	)
	{
		var extraction = GetSingleSourceExtractionExpression(source, variableName, typeName);
		writer.WriteLine(extraction);
	}

	static void WriteSingleSourceExtractionWithDefault(
		CodeWriter writer,
		PropertySource source,
		string variableName,
		string typeName,
		string defaultValueExpression
	)
	{
		var extraction = GetSingleSourceExtractionWithDefaultExpression(
			source,
			variableName,
			typeName,
			defaultValueExpression
		);
		writer.WriteLine(extraction);
	}

	static void WriteMultiSourceExtraction(
		CodeWriter writer,
		ImmutableArray<PropertySource> sources,
		string variableName,
		string typeName,
		bool hasDefaultValue,
		string defaultValueExpression
	)
	{
		writer.WriteLine($"{typeName} {variableName};");

		void WriteFallback(int index)
		{
			if (index >= sources.Length)
			{
				if (hasDefaultValue)
				{
					writer.WriteLine($"{variableName} = {defaultValueExpression};");
				}
				return;
			}

			var source = sources[index];
			var isLast = index == sources.Length - 1 && !hasDefaultValue;
			var methodCall = GetTryGetMethodCall(
				source,
				variableName,
				typeName,
				declareVariable: false
			);

			if (isLast)
			{
				writer.WriteLine(methodCall + ";");
			}
			else
			{
				writer.WriteLine($"if (!{methodCall})");
				writer.WriteBlock(null, body => WriteFallback(index + 1));
			}
		}

		WriteFallback(0);
	}

	static string GetSingleSourceExtractionExpression(
		PropertySource source,
		string variableName,
		string typeName
	)
	{
		var methodCall = GetTryGetMethodCall(source, variableName, typeName, declareVariable: true);
		// TryGet method declares the variable via out var, so we just call it.
		return methodCall + ";";
	}

	static string GetSingleSourceExtractionWithDefaultExpression(
		PropertySource source,
		string variableName,
		string typeName,
		string defaultValueExpression
	)
	{
		return source.Source switch
		{
			AttributePropertySource.NamedArgument =>
				$"var {variableName} = attributeData.GetNamedArgument<{typeName}>(\"{source.MappedName}\", {defaultValueExpression});",
			AttributePropertySource.ConstructorIndex =>
				$"var {variableName} = attributeData.GetConstructorArgument<{typeName}>({source.ConstructorIndex}, {defaultValueExpression});",
			AttributePropertySource.ConstructorName =>
				$"var {variableName} = attributeData.GetConstructorArgument<{typeName}>(\"{source.MappedName}\", {defaultValueExpression});",
			AttributePropertySource.TypeArgument when source.MappedName is not null =>
				$"var {variableName} = attributeData.GetGenericTypeArgument<{typeName}>(\"{source.MappedName}\", {defaultValueExpression});",
			AttributePropertySource.TypeArgument =>
				$"var {variableName} = attributeData.GetGenericTypeArgument<{typeName}>({source.ConstructorIndex}, {defaultValueExpression});",
			_ => throw new InvalidOperationException(
				$"Unsupported property source: {source.Source}"
			),
		};
	}

	static string GetTryGetMethodCall(
		PropertySource source,
		string variableName,
		string typeName,
		bool declareVariable
	)
	{
		var outVariable = declareVariable ? $"out var {variableName}" : $"out {variableName}";
		return source.Source switch
		{
			AttributePropertySource.NamedArgument =>
				$"attributeData.TryGetNamedArgument<{typeName}>(\"{source.MappedName}\", {outVariable})",
			AttributePropertySource.ConstructorIndex =>
				$"attributeData.TryGetConstructorArgument<{typeName}>({source.ConstructorIndex}, {outVariable})",
			AttributePropertySource.ConstructorName =>
				$"attributeData.TryGetConstructorArgument<{typeName}>(\"{source.MappedName}\", {outVariable})",
			AttributePropertySource.TypeArgument when source.MappedName is not null =>
				$"attributeData.TryGetGenericTypeArgument<{typeName}>(\"{source.MappedName}\", {outVariable})",
			AttributePropertySource.TypeArgument =>
				$"attributeData.TryGetGenericTypeArgument<{typeName}>({source.ConstructorIndex}, {outVariable})",
			_ => throw new InvalidOperationException(
				$"Unsupported property source: {source.Source}"
			),
		};
	}

	static string GetNonNullableTypeName(string typeName) =>
		typeName.EndsWith("?", StringComparison.Ordinal)
			? typeName.Substring(0, typeName.Length - 1)
			: typeName;

	static string ToCamelCase(string value) =>
		string.IsNullOrEmpty(value) ? value : char.ToLowerInvariant(value[0]) + value.Substring(1);

	void Abstractions.ILogSupport.SetLogOutput(
		global::System.Action<string, Abstractions.OutputType> action
	) => _logger = new Abstractions.GenerationLogger(action);
}
