using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Purview.SourceGeneratorFramework.Testing.Generators;

[Generator]
public sealed class LoggingSupportGenerator : IIncrementalGenerator
{
	const string LogSupportNamespace = "Purview.SourceGeneratorFramework.Testing.Abstractions";
	const string LogSupportInterfaceName = LogSupportNamespace + ".ILogSupport";
	const string IncrementalGeneratorInterfaceName = "Microsoft.CodeAnalysis.IIncrementalGenerator";
	const string SourceGeneratorInterfaceName = "Microsoft.CodeAnalysis.ISourceGenerator";

	const string EmbeddedAttributeName = "Microsoft.CodeAnalysis.EmbeddedAttribute";

	const string EmbeddedAttributeSource =
		@"namespace Microsoft.CodeAnalysis;

sealed partial class EmbeddedAttribute : global::System.Attribute
{
}
";

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(static postInitContext =>
			postInitContext.AddSource(
				EmbeddedAttributeName + ".g.cs",
				SourceText.From(EmbeddedAttributeSource, Encoding.UTF8)
			)
		);

		var generatorClasses = context
			.SyntaxProvider.CreateSyntaxProvider(
				predicate: static (node, _) => node is ClassDeclarationSyntax,
				transform: static (ctx, ct) => GetGeneratorClassInfo(ctx, ct)
			)
			.Where(static info => info is not null)
			.Collect();

		context.RegisterSourceOutput(
			generatorClasses,
			static (spc, classes) =>
			{
				foreach (var classInfo in classes.Distinct())
				{
					if (classInfo is null)
						continue;

					GenerateLogSupport(spc, classInfo.Value);
				}
			}
		);
	}

	static ClassInfo? GetGeneratorClassInfo(
		GeneratorSyntaxContext context,
		CancellationToken cancellationToken
	)
	{
		var classSyntax = (ClassDeclarationSyntax)context.Node;
		var symbol = context.SemanticModel.GetDeclaredSymbol(classSyntax, cancellationToken);

		if (symbol is not INamedTypeSymbol { IsAbstract: false, IsStatic: false } typeSymbol)
			return null;

		var interfaces = typeSymbol.AllInterfaces;
		var isGenerator = interfaces.Any(static i =>
			i.ToDisplayString() is IncrementalGeneratorInterfaceName or SourceGeneratorInterfaceName
		);

		if (!isGenerator)
			return null;

		var hasLogSupport = interfaces.Any(static i =>
			i.ToDisplayString() == LogSupportInterfaceName
		);

		if (hasLogSupport)
			return null;

		// If we reach this point, the class is a non-abstract, non-static class that implements
		// IIncrementalGenerator or ISourceGenerator but does not implement ILogSupport. We can generate the logging support for it.
		return new(
			typeSymbol.ContainingNamespace.IsGlobalNamespace
				? null
				: typeSymbol.ContainingNamespace.ToDisplayString(),
			typeSymbol.Name,
			classSyntax.Modifiers.Any(SyntaxKind.PartialKeyword)
		);
	}

	static void GenerateLogSupport(SourceProductionContext context, ClassInfo classInfo)
	{
		if (!classInfo.IsPartial)
		{
			context.ReportDiagnostic(
				Diagnostic.Create(
					new DiagnosticDescriptor(
						"PSG0001",
						"Source generator must be partial",
						"Class '{0}' implements a source generator interface but is not marked partial. Logging support cannot be generated.",
						"Purview.SourceGenerators.Testing",
						DiagnosticSeverity.Warning,
						true
					),
					Location.None,
					classInfo.Name
				)
			);
			return;
		}

		var namespaceDeclaration = string.IsNullOrEmpty(classInfo.Namespace)
			? string.Empty
			: $"namespace {classInfo.Namespace};\n\n";

		var source =
			$@"// <auto-generated />

#nullable enable
{namespaceDeclaration}using System;

[global::{EmbeddedAttributeName}]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.CodeDom.Compiler.GeneratedCode(""{AssemblyInfo.AssemblyName}"", ""{AssemblyInfo.Version}"")]
partial class {classInfo.Name} : global::Purview.SourceGeneratorFramework.Testing.Abstractions.ILogSupport
{{
	global::Purview.SourceGeneratorFramework.Testing.Abstractions.GenerationLogger? _logger;

	void global::Purview.SourceGeneratorFramework.Testing.Abstractions.ILogSupport.SetLogOutput(global::System.Action<string, global::Purview.SourceGeneratorFramework.Testing.Abstractions.OutputType> action) =>
		_logger = new global::Purview.SourceGeneratorFramework.Testing.Abstractions.GenerationLogger(action);
}}
";

		context.AddSource($"{classInfo.Name}.LogSupport.g.cs", source);
	}

	readonly struct ClassInfo(string? @namespace, string name, bool isPartial)
		: IEquatable<ClassInfo>
	{
		public string? Namespace { get; } = @namespace;

		public string Name { get; } = name;

		public bool IsPartial { get; } = isPartial;

		public bool Equals(ClassInfo other) =>
			Namespace == other.Namespace && Name == other.Name && IsPartial == other.IsPartial;

		public override bool Equals(object? obj) => obj is ClassInfo other && Equals(other);

		public override int GetHashCode()
		{
			var hash = 17;
			hash = (hash * 31) + (Namespace?.GetHashCode() ?? 0);
			hash = (hash * 31) + Name.GetHashCode();
			hash = (hash * 31) + IsPartial.GetHashCode();
			return hash;
		}
	}
}
