using Microsoft.CodeAnalysis;
using Purview.SourceGeneratorFramework.Testing.Abstractions;

namespace Purview.SourceGeneratorFramework.Testing.Generators;

[Generator]
public sealed partial class LoggingSupportGenerator : IIncrementalGenerator, ILogSupport
{
	GenerationLogger? _logger;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var generationModel = SourceGenLibrary.GetGeneratorValueProviders(context, _logger);

		context.RegisterSourceOutput(
			generationModel,
			(spc, model) =>
			{
				if (model.IsDisabled)
				{
					_logger?.Info("Logging support generation is disabled.");
					return;
				}

				foreach (var sourceGenType in model.SourceGenerators.Distinct())
				{
					if (sourceGenType.HasDiagnostics)
						spc.ReportDiagnostics(sourceGenType.Diagnostics);

					if (sourceGenType.IsFatal)
						continue;

					GenerateLogSupport(spc, sourceGenType.Value, _logger);
				}
			}
		);
	}

	static void GenerateLogSupport(
		SourceProductionContext context,
		TypeValueObject sourceGenType,
		GenerationLogger? logger
	)
	{
		logger?.Info(
			$"Generating logging support for class '{sourceGenType.TypeName}' in namespace '{sourceGenType.Namespace ?? "<global>"}'."
		);

		CodeWriter writer = new();
		writer
			.WriteAutoGeneratedHeader(nameof(LoggingSupportGenerator), AssemblyInfo.Version)
			.WriteFileScopedNamespace(sourceGenType.Namespace);

		writer
			.WriteLine("[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]")
			.WriteLine("[global::System.Runtime.CompilerServices.CompilerGenerated]")
			.Write("[global::System.CodeDom.Compiler.GeneratedCode(")
			.Quote(AssemblyInfo.AssemblyName)
			.Write(", ")
			.Quote(AssemblyInfo.Version)
			.WriteLine(")]");

		using (
			var classWriter = writer.WriteClass(
				new TypeDeclarationOptions(sourceGenType) { Interfaces = [TypeLibrary.ILogSupport] }
			)
		)
		{
			writer.Write(TypeLibrary.GenerationLogger).WriteLine("? _logger;").NewLine();

			writer
				.Write("void")
				.Write(' ')
				.Write(TypeLibrary.ILogSupport)
				.Write('.')
				.Write(nameof(ILogSupport.SetLogOutput))
				.Write('(')
				.Write("global::System.Action<string, ")
				.Write(TypeLibrary.OutputType)
				.WriteLine("> action) =>")
				.Indent()
				.Write("_logger = new ")
				.Write(TypeLibrary.GenerationLogger)
				.WriteLine("(action);")
				.Unindent();
		}

		context.AddSource($"{sourceGenType.TypeName}.LogSupport.g.cs", writer);
	}

	void ILogSupport.SetLogOutput(Action<string, OutputType> action) => _logger = new(action);
}
