using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Purview.SourceGeneratorFramework.Logging;

namespace Purview.SourceGeneratorFramework.Generators;

[Generator]
public sealed class AttributeDataModelGenerator : IIncrementalGenerator, ILogSupport
{
	GenerationLogger? _logger;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterEmbeddedAttribute(
			typeof(AttributeDataModelGenerator).FullName!,
			AssemblyInfo.Version
		);

		context.RegisterPostInitializationOutput(context =>
		{
			var attributeSource = EmbeddedResources.Load("AttributeDataModelAttributes");
			context.AddSource("AttributeDataModelAttributes.g.cs", attributeSource);
		});

		var targets = AttributeDataModelLibrary.GetTargets(context, _logger);
		var isDisabled = IncrementalPipeline.IsDisabledValueProvider(
			context,
			PropertyLibrary.DisableAttributeDataSourceGenerator
		);

		context.RegisterSourceOutput(
			targets.Combine(isDisabled),
			(spc, input) =>
			{
				if (input.Right)
				{
					_logger?.Info("AttributeDataModelGenerator is disabled.");
					return;
				}

				var target = input.Left;
				if (target.HasDiagnostics)
					spc.ReportDiagnostics(target.Diagnostics);

				if (target.IsFatal || target.IsEmpty)
					return;

				GenerateAttributeDataModel(spc, target.Value!);
			}
		);
	}

	static void GenerateAttributeDataModel(
		SourceProductionContext spc,
		AttributeDataModelTarget target
	)
	{
		var writer = new CodeWriter(
			generatorName: typeof(AttributeDataModelGenerator).FullName,
			generatorVersion: AssemblyInfo.Version
		);
		writer.WriteAutoGeneratedHeader();
		writer.WriteUsing("System.Collections.Immutable");
		writer.WriteUsing("Microsoft.CodeAnalysis");
		writer.WriteUsing("Purview.SourceGeneratorFramework.Extensions");
		writer.WriteUsing("Purview.SourceGeneratorFramework.Helpers");
		writer.WriteUsing("Purview.SourceGeneratorFramework.Models");

		if (string.IsNullOrEmpty(target.Namespace))
		{
			WriteStruct(writer, target);
		}
		else
		{
			using (writer.WriteBlockNamespaceScope(target.Namespace))
				WriteStruct(writer, target);
		}

		spc.AddSource($"{target.StructName}.AttributeDataModel.g.cs", writer);
	}

	static void WriteStruct(CodeWriter writer, AttributeDataModelTarget target)
	{
		TypeDeclarationOptions options = new(target.StructName)
		{
			Accessibility = target.Accessibility,
			IsReadOnly = true,
			IsPartial = true,
		};

		using (writer.WriteRecordStructScope(options))
		{
			writer.WriteProperty(
				new("Exists", "bool") { Accessibility = TypeDeclarationAccessibility.Public }
			);
			foreach (var property in target.Properties)
			{
				if (property.IsExplicit)
					continue;

				writer.WriteProperty(
					new(property.PropertyName, property.FullyQualifiedTypeName)
					{
						Accessibility = TypeDeclarationAccessibility.Public,
						HasSetter = true,
						IsInitOnly = true,
					}
				);
			}
			WriteConstructor(writer, target);
			WriteTargetAttributeField(writer, target);
			WriteEmptyField(writer, target);
			WriteFromAttributeDataArrayMethod(writer, target);
			WriteFromAttributeDataArrayWithOutMethod(writer, target);
			WriteFromAttributeDataMethod(writer, target);
		}
	}

	static void WriteConstructor(CodeWriter writer, AttributeDataModelTarget target)
	{
		var parameters = ImmutableArray.CreateBuilder<ParameterDeclarationOptions>();
		parameters.Add(new("Exists", "bool"));
		foreach (var property in target.Properties)
		{
			parameters.Add(new(property.PropertyName, property.FullyQualifiedTypeName));
		}

		writer.WriteConstructor(
			new(target.StructName)
			{
				Accessibility = TypeDeclarationAccessibility.Public,
				Parameters = [.. parameters],
				Initializer = GetPrimaryConstructorInitializer(target),
			},
			body =>
			{
				body.WriteLine("this.Exists = Exists;");
				foreach (var property in target.Properties)
				{
					if (!property.IsExplicit)
						body.WriteLine($"this.{property.PropertyName} = {property.PropertyName};");
				}
			}
		);
	}

	static string? GetPrimaryConstructorInitializer(AttributeDataModelTarget target)
	{
		var arguments = target
			.Properties.Where(static property => property.IsExplicit)
			.Select(static property => property.PropertyName)
			.ToArray();

		return arguments.Length == 0 ? null : $"this({string.Join(", ", arguments)})";
	}

	static void WriteTargetAttributeField(CodeWriter writer, AttributeDataModelTarget target)
	{
		var namespaceValue = target.TargetAttribute.Namespace is null
			? "null"
			: $"\"{target.TargetAttribute.Namespace}\"";

		writer.WriteField(
			new("TargetAttribute", GeneratorTypeLibrary.TypeValueObject)
			{
				Accessibility = TypeDeclarationAccessibility.Public,
				IsStatic = true,
				IsReadOnly = true,
				Initializer = $"new(\"{target.TargetAttribute.TypeName}\", {namespaceValue})",
			}
		);
	}

	static void WriteEmptyField(CodeWriter writer, AttributeDataModelTarget target)
	{
		var values = new List<string> { "false" };
		foreach (var property in target.Properties)
		{
			var value = $"default({property.FullyQualifiedTypeName})";
			if (property.IsNonNullableReferenceType)
				value += "!";

			values.Add(value);
		}

		writer.WriteField(
			new FieldDeclarationOptions("Empty", target.StructName)
			{
				Accessibility = TypeDeclarationAccessibility.Public,
				IsStatic = true,
				IsReadOnly = true,
				Initializer = $"new({string.Join(", ", values)})",
			}
		);
	}

	static void WriteFromAttributeDataArrayMethod(
		CodeWriter writer,
		AttributeDataModelTarget target
	)
	{
		MethodDeclarationOptions methodOptions = new("FromAttributeData", new(target.StructName))
		{
			Accessibility = TypeDeclarationAccessibility.Public,
			IsStatic = true,
			Parameters =
			[
				new(
					"attributes",
					new(
						"global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.AttributeData>"
					)
				),
			],
		};

		writer.WriteMethod(
			methodOptions,
			w =>
			{
				w.WriteLine("for (var i = 0; i < attributes.Length; i++)");
				w.WriteBlock(
					null,
					body =>
					{
						body.WriteLine("var result = FromAttributeData(attributes[i]);");
						body.WriteLine("if (result.Exists)");
						body.WriteBlock(null, inner => inner.WriteLine("return result;"));
					}
				);
				w.WriteLine("return Empty;");
			}
		);
	}

	static void WriteFromAttributeDataArrayWithOutMethod(
		CodeWriter writer,
		AttributeDataModelTarget target
	)
	{
		var methodOptions = new MethodDeclarationOptions(
			"FromAttributeData",
			new(target.StructName)
		)
		{
			Accessibility = TypeDeclarationAccessibility.Public,
			IsStatic = true,
			Parameters =
			[
				new(
					"attributes",
					new(
						"global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.AttributeData>"
					)
				),
				new("attribute", new("global::Microsoft.CodeAnalysis.AttributeData?"))
				{
					Modifier = ParameterModifier.Out,
				},
			],
		};

		writer.WriteMethod(
			methodOptions,
			w =>
			{
				w.WriteLine("attribute = null;");
				w.WriteLine("for (var i = 0; i < attributes.Length; i++)");
				w.WriteBlock(
					null,
					body =>
					{
						body.WriteLine("var result = FromAttributeData(attributes[i]);");
						body.WriteLine("if (result.Exists)");
						body.WriteBlock(
							null,
							inner =>
							{
								inner.WriteLine("attribute = attributes[i];");
								inner.WriteLine("return result;");
							}
						);
					}
				);
				w.WriteLine("return Empty;");
			}
		);
	}

	static void WriteFromAttributeDataMethod(CodeWriter writer, AttributeDataModelTarget target)
	{
		var methodOptions = new MethodDeclarationOptions(
			"FromAttributeData",
			new(target.StructName)
		)
		{
			Accessibility = TypeDeclarationAccessibility.Public,
			IsStatic = true,
			Parameters =
			[
				new("attributeData", new("global::Microsoft.CodeAnalysis.AttributeData")),
			],
		};

		writer.WriteMethod(
			methodOptions,
			w =>
			{
				if (target.MatchByInheritance)
				{
					w.WriteLine(
						"if (attributeData.AttributeClass is null || (!TargetAttribute.Equals(attributeData.AttributeClass) && !global::Purview.SourceGeneratorFramework.Helpers.TypeHelpers.InheritsFrom(attributeData.AttributeClass, TargetAttribute)))"
					);
				}
				else
				{
					w.WriteLine("if (!TargetAttribute.Equals(attributeData.AttributeClass))");
				}
				w.WriteBlock(null, body => body.WriteLine("return Empty;"));

				foreach (var property in target.Properties)
				{
					WritePropertyExtraction(w, property);
				}

				var returnValues = new List<string> { "true" };
				foreach (var property in target.Properties)
				{
					var value = ToCamelCase(property.PropertyName);
					returnValues.Add(property.IsNonNullableReferenceType ? value + "!" : value);
				}

				w.WriteLine($"return new({string.Join(", ", returnValues)});");
			}
		);
	}

	static void WritePropertyExtraction(CodeWriter writer, AttributeDataModelProperty property)
	{
		var variableName = ToCamelCase(property.PropertyName);
		var typeName = GetNonNullableTypeName(property.FullyQualifiedTypeName);
		var localTypeName = property.IsNonNullableReferenceType
			? typeName + "?"
			: property.FullyQualifiedTypeName;

		if (property.IsNestedModel)
		{
			writer.WriteLine(
				$"var {variableName} = {property.NestedModelTypeName}.FromAttributeData(attributeData);"
			);
			return;
		}

		if (property.IsEnum)
		{
			WriteEnumPropertyExtraction(writer, property, variableName);
			return;
		}

		var sources = property.Sources;
		if (sources.IsEmpty)
		{
			writer.WriteLine($"var {variableName} = default({typeName});");
			return;
		}

		if (sources.Length == 1)
		{
			var source = sources[0];
			if (property.HasDefaultValue)
			{
				WriteSingleSourceExtractionWithDefault(
					writer,
					source,
					variableName,
					typeName,
					property.DefaultValueExpression
				);
			}
			else
			{
				WriteSingleSourceExtraction(writer, source, variableName, typeName);
			}
			return;
		}

		WriteMultiSourceExtraction(
			writer,
			sources,
			variableName,
			typeName,
			localTypeName,
			property.HasDefaultValue,
			property.DefaultValueExpression
		);
	}

	static void WriteSingleSourceExtraction(
		CodeWriter writer,
		PropertySource source,
		string variableName,
		string typeName
	)
	{
		var extraction = GetSingleSourceExtractionExpression(source, variableName, typeName);
		writer.WriteLine(extraction);
	}

	static void WriteSingleSourceExtractionWithDefault(
		CodeWriter writer,
		PropertySource source,
		string variableName,
		string typeName,
		string defaultValueExpression
	)
	{
		var extraction = GetSingleSourceExtractionWithDefaultExpression(
			source,
			variableName,
			typeName,
			defaultValueExpression
		);
		writer.WriteLine(extraction);
	}

	static void WriteMultiSourceExtraction(
		CodeWriter writer,
		ImmutableArray<PropertySource> sources,
		string variableName,
		string typeName,
		string localTypeName,
		bool hasDefaultValue,
		string defaultValueExpression
	)
	{
		writer.WriteLine($"{localTypeName} {variableName};");

		void WriteFallback(int index)
		{
			if (index >= sources.Length)
			{
				if (hasDefaultValue)
				{
					writer.WriteLine($"{variableName} = {defaultValueExpression};");
				}
				return;
			}

			var source = sources[index];
			var isLast = index == sources.Length - 1 && !hasDefaultValue;
			var methodCall = GetTryGetMethodCall(
				source,
				variableName,
				typeName,
				declareVariable: false
			);

			if (isLast)
			{
				writer.WriteLine(methodCall + ";");
			}
			else
			{
				writer.WriteLine($"if (!{methodCall})");
				writer.WriteBlock(null, body => WriteFallback(index + 1));
			}
		}

		WriteFallback(0);
	}

	static void WriteEnumPropertyExtraction(
		CodeWriter writer,
		AttributeDataModelProperty property,
		string variableName
	)
	{
		var sources = property.Sources;
		var defaultValueExpression = property.HasDefaultValue
			? property.DefaultValueExpression
			: "null";

		if (sources.Length == 1)
		{
			var expression = GetEnumSingleSourceExtractionExpression(
				sources[0],
				defaultValueExpression
			);
			writer.WriteLine($"var {variableName} = {expression};");
			return;
		}

		WriteEnumMultiSourceExtraction(writer, sources, variableName, defaultValueExpression);
	}

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	static string GetEnumSingleSourceExtractionExpression(
		PropertySource source,
		string defaultValueExpression
	)
	{
		return source.Source switch
		{
			AttributePropertySource.NamedArgument =>
				$"attributeData.GetEnumNamedArgument(\"{source.MappedName}\", {defaultValueExpression})",
			AttributePropertySource.ConstructorIndex =>
				$"attributeData.GetEnumConstructorArgument({source.ConstructorIndex}, {defaultValueExpression})",
			AttributePropertySource.ConstructorName =>
				$"attributeData.GetEnumConstructorArgument(\"{source.MappedName}\", {defaultValueExpression})",
			_ => throw new InvalidOperationException(
				$"Unsupported enum property source: {source.Source}"
			),
		};
	}

	static void WriteEnumMultiSourceExtraction(
		CodeWriter writer,
		ImmutableArray<PropertySource> sources,
		string variableName,
		string defaultValueExpression
	)
	{
		var typeName = "global::Microsoft.CodeAnalysis.TypedConstant";
		var tempName = $"__{variableName}Tc";

		writer.WriteLine($"{typeName}? {tempName} = default;");

		void WriteFallback(int index)
		{
			if (index >= sources.Length)
			{
				writer.WriteLine($"{tempName} = default;");
				return;
			}

			var source = sources[index];
			var isLast = index == sources.Length - 1;
			var methodCall = GetTryGetMethodCall(
				source,
				tempName,
				typeName,
				declareVariable: false
			);

			if (isLast)
			{
				writer.WriteLine(methodCall + ";");
			}
			else
			{
				writer.WriteLine($"if (!{methodCall})");
				writer.WriteBlock(null, body => WriteFallback(index + 1));
			}
		}

		WriteFallback(0);

		writer.WriteLine(
			$"var {variableName} = {tempName}.ToEnumString({defaultValueExpression});"
		);
	}

	static string GetSingleSourceExtractionExpression(
		PropertySource source,
		string variableName,
		string typeName
	)
	{
		var methodCall = GetTryGetMethodCall(source, variableName, typeName, declareVariable: true);
		// TryGet method declares the variable via out var, so we just call it.
		return methodCall + ";";
	}

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	static string GetSingleSourceExtractionWithDefaultExpression(
		PropertySource source,
		string variableName,
		string typeName,
		string defaultValueExpression
	)
	{
		return source.Source switch
		{
			AttributePropertySource.NamedArgument =>
				$"var {variableName} = attributeData.GetNamedArgument<{typeName}>(\"{source.MappedName}\", {defaultValueExpression});",
			AttributePropertySource.ConstructorIndex =>
				$"var {variableName} = attributeData.GetConstructorArgument<{typeName}>({source.ConstructorIndex}, {defaultValueExpression});",
			AttributePropertySource.ConstructorName =>
				$"var {variableName} = attributeData.GetConstructorArgument<{typeName}>(\"{source.MappedName}\", {defaultValueExpression});",
			AttributePropertySource.TypeArgument when source.MappedName is not null =>
				$"var {variableName} = attributeData.GetGenericTypeArgument<{typeName}>(\"{source.MappedName}\", {defaultValueExpression});",
			AttributePropertySource.TypeArgument =>
				$"var {variableName} = attributeData.GetGenericTypeArgument<{typeName}>({source.ConstructorIndex}, {defaultValueExpression});",
			_ => throw new InvalidOperationException(
				$"Unsupported property source: {source.Source}"
			),
		};
	}

	[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0072:Add missing cases")]
	static string GetTryGetMethodCall(
		PropertySource source,
		string variableName,
		string typeName,
		bool declareVariable
	)
	{
		var outVariable = declareVariable ? $"out var {variableName}" : $"out {variableName}";
		return source.Source switch
		{
			AttributePropertySource.NamedArgument =>
				$"attributeData.TryGetNamedArgument<{typeName}>(\"{source.MappedName}\", {outVariable})",
			AttributePropertySource.ConstructorIndex =>
				$"attributeData.TryGetConstructorArgument<{typeName}>({source.ConstructorIndex}, {outVariable})",
			AttributePropertySource.ConstructorName =>
				$"attributeData.TryGetConstructorArgument<{typeName}>(\"{source.MappedName}\", {outVariable})",
			AttributePropertySource.TypeArgument when source.MappedName is not null =>
				$"attributeData.TryGetGenericTypeArgument<{typeName}>(\"{source.MappedName}\", {outVariable})",
			AttributePropertySource.TypeArgument =>
				$"attributeData.TryGetGenericTypeArgument<{typeName}>({source.ConstructorIndex}, {outVariable})",
			_ => throw new InvalidOperationException(
				$"Unsupported property source: {source.Source}"
			),
		};
	}

	static string GetNonNullableTypeName(string typeName) =>
		typeName.EndsWith("?", StringComparison.Ordinal)
			? typeName.Substring(0, typeName.Length - 1)
			: typeName;

	static string ToCamelCase(string value) =>
		string.IsNullOrEmpty(value) ? value : char.ToLowerInvariant(value[0]) + value.Substring(1);

	void ILogSupport.SetLogOutput(Action<string, OutputType> action) => _logger = new(action);
}
