using Microsoft.CodeAnalysis;
using Purview.SourceGeneratorFramework.Logging;

namespace Purview.SourceGeneratorFramework.Generators;

[Generator]
public sealed partial class LoggingSupportGenerator : IIncrementalGenerator, ISupportsSourceGenLogging
{
	ISourceGenLogger? _logger;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		context.RegisterPostInitializationOutput(context =>
		{
			_logger?.Info("Generating logging support source code:");
			foreach (var (hintName, source) in SourceEmitter.LoggingEmit())
			{
				_logger?.Info($"- {hintName}", 1);
				context.AddSource(hintName, source);
			}
		});

		var isDisabled = IncrementalPipeline.IsDisabledValueProvider(
			context,
			PropertyLibrary.DisableLoggingSourceGenerator
		);
		var sourceGenerators = SourceGenLibrary.GetGeneratorValueProviders(context);

		context.RegisterSourceOutput(
			sourceGenerators.Combine(isDisabled),
			(spc, input) =>
			{
				if (input.Right)
				{
					_logger?.Info("Logging support generation is disabled.");
					return;
				}

				var sourceGenType = input.Left;
				if (sourceGenType.HasDiagnostics)
					spc.ReportDiagnostics(sourceGenType.Diagnostics);

				if (sourceGenType.IsFatal)
					return;

				GenerateLogSupport(spc, sourceGenType.Value!, _logger);
			}
		);
	}

	static void GenerateLogSupport(
		SourceProductionContext context,
		TypeValueObject sourceGenType,
		ISourceGenLogger? logger
	)
	{
		logger?.Info(
			$"Generating logging support for class '{sourceGenType.TypeName}' in namespace '{sourceGenType.Namespace ?? "<global>"}'."
		);

		var writer = new CodeWriter(typeof(LoggingSupportGenerator).FullName, AssemblyInfo.Version);
		writer.WriteAutoGeneratedHeader().WriteFileScopedNamespace(sourceGenType.Namespace);

		using (
			var classWriter = writer.WriteClassScope(
				new TypeDeclarationOptions(sourceGenType)
				{
					Interfaces = [new TypeReferenceOptions(GeneratorTypeLibrary.Logging.ISupportsSourceGenLogging)],
				}
			)
		)
		{
			writer.Write(GeneratorTypeLibrary.Logging.ISourceGenLogger).WriteLine("? _logger;").NewLine();

			writer
				.Write("void")
				.Write(' ')
				.Write(GeneratorTypeLibrary.Logging.ISupportsSourceGenLogging)
				.Write('.')
				.Write(nameof(ISupportsSourceGenLogging.SetOutput))
				.Write('(')
				.Write("global::System.Action<string, ")
				.Write(GeneratorTypeLibrary.Logging.SourceGenLogLevel)
				.WriteLine("> action) =>")
				.Indent()
				.Write("_logger = new ")
				.Write(GeneratorTypeLibrary.Logging.SourceGenLogger)
				.WriteLine("(action);")
				.Unindent();
		}

		context.AddSource($"{sourceGenType.TypeName}.LogSupport.g.cs", writer);
	}

	void ISupportsSourceGenLogging.SetOutput(Action<string, SourceGenLogLevel> action) =>
		_logger = new SourceGenLogger(action);
}
