<Project>
	<PropertyGroup Condition="'$(IsPackable)' == 'true'">
		<Authors>Purview Contributors</Authors>
		<Description>Purview SourceGeneratorFramework libraries for building and testing incremental C# source generators.</Description>
		<PackageProjectUrl>https://github.com/purview-dev/purview-sourcegeneratorframework</PackageProjectUrl>
		<RepositoryUrl>https://github.com/purview-dev/purview-sourcegeneratorframework</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>purview-logo.jpg</PackageIcon>
		<PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup Label="NuGet package assets" Condition="'$(IsPackable)' == 'true'">
		<None
			Include="$(MSBuildThisFileDirectory)../assets/images/purview-logo.jpg"
			Pack="true"
			PackagePath="/"
			Visible="false"
		/>
	</ItemGroup>

	<Import Sdk="Purview.DotNetProjectSdk" Project="Sdk.targets" />
</Project>
