<Project>
	<PropertyGroup>
		<TargetFrameworks>netstandard2.1;net8.0;net9.0;net10.0;</TargetFrameworks>
		<NamespacePrefix>Purview.SourceGeneratorFramework</NamespacePrefix>
		<!-- Set project-by-project -->
		<IsPackable>false</IsPackable>
		<ExcludePurviewTelemetry>true</ExcludePurviewTelemetry>
		<RepositoryUrl>https://github.com/purview-dev/purview-sourcegeneratorframework</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<SourceGeneratorFrameworkRoslynInnerBuild
			Condition="'$(SourceGeneratorFrameworkRoslynInnerBuild)' == ''"
			>false</SourceGeneratorFrameworkRoslynInnerBuild>
		<BaseIntermediateOutputPath
			Condition="'$(SourceGeneratorFrameworkRoslynInnerBuild)' == 'true'"
			>obj\$(Configuration)\roslyn$(RoslynCompilerVersion)\</BaseIntermediateOutputPath>
		<BaseOutputPath Condition="'$(SourceGeneratorFrameworkRoslynInnerBuild)' == 'true'"
			>bin\$(Configuration)\roslyn$(RoslynCompilerVersion)\</BaseOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<!--
			- CA1510 is because of .NET Standard, we can't use APIs such as
				ArgumentNullException.ThrowIfNull()
		-->
		<NoWarn>$(NoWarn);CA1031;CA1510;</NoWarn>
	</PropertyGroup>

	<Import Sdk="Purview.DotNetProjectSdk" Project="Sdk.props" />

	<PropertyGroup Condition="'$(IsTestProject)' == 'true'">
		<!-- Test projects aren't executable so we need to remove .NET Standard 2.1 -->
		<TargetFrameworks>net8.0;net9.0;net10.0;</TargetFrameworks>
	</PropertyGroup>

	<PropertyGroup Condition="'$(IsPackable)' == 'true'">
		<Authors>Purview Contributors</Authors>
		<PackageProjectUrl>https://github.com/purview-dev/purview-sourcegeneratorframework</PackageProjectUrl>
		<RepositoryUrl>https://github.com/purview-dev/purview-sourcegeneratorframework</RepositoryUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
</Project>
